name: HACS Validation

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - version-0.7.x
  pull_request:
    branches:
      - master
      - version-0.7.x
  schedule:
    - cron: "0 2 * * *"

jobs:
  hacs:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "integration"
